
module.exports = {
  TWITTER_URL: "https://twitter.com/",
  MEMCACHE_TWEET_KEY: "TWEETS.",
  MEMCACHE_USER_KEY: "USER.",
  TWEETS_TO_FETCH: 30,
  MIN_RATIO: 0.10,
  MAX_PUT_SIZE: 500,
  MAX_API_LOOKUP_SIZE: 100,
  MIN_SEARCH_LENGTH: 2,
  ARCHIVE_TIME_FORMAT: "2006-01-02 15:04:05 -0700",
  TWEETS_KEY: "MyTweet",
  USERS_KEY: "User",
  SEARCH_LIMIT: 1000,
  SUMMARY_LENGTH: 30,
  HAS_MORE: Symbol("tapp-has-more-cursor"),
};
